### PR TITLE
Remove installation instructions from readme

### PR DESCRIPTION
**Pull request by kevmoo**
Covered here https://github.com/phosphor-icons/phosphor-flutter/blob/main/README.md

### CODE REVIEW

**Comment by rektdeckard** [comment]
But you're deleting the instructions? Not sure I follow...

**Comment by kevmoo** [comment]
Ah! Wrong link https://pub.dev/packages/phosphor_flutter/install

There are already install instructions generated on the pub.dev site.

**Comment by rektdeckard** [comment]
I thiiink we can keep it duplicated here, for the benefit of people stumbling across the repo before the pub.dev page. But as a non flutter dev I can't say whether this is necessary or not.

**Comment by kevmoo** [comment]
okay

**Pull request closed without merging**
